name: Promote NPM package
on:
  pull_request:
    paths:
      - "packages/client/package.json"
    branches:
      - develop
      - main

jobs:
  develop:
    name: Promote develop NPM package
    runs-on: ubuntu-latest
    if: ${{ github.head_ref == 'refs/heads/develop' }}
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
    - uses: actions/checkout@v3


    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'


    - name: Publish package
      run: |
        cd packages/client 
        VERSION=$(node -p "require('./package.json').version")
        VERSIONREMOTE=$(npm view polyapi --json | jq -r '.["dist-tags"].na1')
        VERSIONREMOTELATEST=$(npm view polyapi --json | jq -r '.["dist-tags"].latest')
        
        if [[ $VERSION == $VERSIONREMOTE ]]; then
          npm dist-tag add polyapi@$VERSION na1 
        else
          echo "Repository NPM version it's the same that na1 on registry"
        fi
        
        if [[ $VERSION == $VERSIONREMOTELATEST ]]; then
          npm dist-tag add polyapi@$VERSION latest 
        else
          echo "Repository NPM version it's the same that latest on registry"
        fi


  main:
    name: Tagging of develop package
    runs-on: ubuntu-latest
    if: ${{ github.head_ref == 'refs/heads/main' }}
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


    steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'


    - name: Publish package
      run: |
        cd packages/client
        VERSION=$(node -p "require('./package.json').version")
        VERSIONREMOTE=$(npm view polyapi --json | jq -r '.["dist-tags"].develop')

        if [[ $VERSION == $VERSIONREMOTE ]]; then
          npm dist-tag add polyapi@$VERSION develop
        else
          echo "Repository NPM version it's the same that develop on registry"
        fi


