name: Promote NPM package
on:
  pull_request:
    paths:
      - "packages/client/package.json"
    branches:
      - develop
      - main

jobs:
  develop:
    name: Promote develop NPM package
    runs-on: ubuntu-latest
    if: ${{ github.head_ref == 'refs/heads/develop' }}
      
    steps:
    - uses: actions/checkout@v3


    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'


    - name: Publish package
      run: VERSION=$(node -p "require('./package.json').version") && npm dist-tag add polyapi@$VERSION na1 && npm dist-tag add polyapi@$VERSION latest
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  main:
    name: Tagging of develop package
    runs-on: ubuntu-latest
    if: ${{ github.head_ref == 'refs/heads/main' }}

      
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'


    - name: Publish package
      run: VERSION=$(node -p "require('./package.json').version") && npm dist-tag add polyapi@$VERSION develop
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
